### PR TITLE
v4.0.0

### PR DESCRIPTION
**Pull request by MurhafSousli**

### CODE REVIEW

**Comment by harm-less** [comment]
In the beta right now the "ImageItem" class is not an exported member of the "@ngx-gallery/core" package. I guess it's not the only one, so I think there a fundamental issue currently. Could this be the case?

**Comment by MurhafSousli** [comment]
@harm-less it is exported! https://github.com/MurhafSousli/ngx-gallery/blob/master/projects/core/src/public_api.ts#L6

**Comment by harm-less** [comment]
Mm, ok, I could be me (or my IDE) after upgrading to the beta, but I could swear it wasn't there. It's not a big deal though, I just thought you should know 😊

**Comment by MurhafSousli** [comment]
@harm-less No problem 😄

**Pull request merged**
