### PR TITLE
Fixes vertical scroll on touch devices #161

### LINKED ISSUE #161: Vertical scroll is not working on gallery on touch device
#### What is the expected behavior?

Vertical scroll on mobile device is not prevented.

#### What is the current behavior?

Gallery prevents vertical scrolling on mobile devices with hammerjs.

#### What are the steps to reproduce?

Open https://murhafsousli.github.io/ngx-gallery/#/gallery, switch to mobile mode in dev console, scroll down to the gallery.

#### Workaround with its own downsides exists

Set `Hammer.defaults.touchAction = 'pan-y';`. Issues with this approach: 
* this is global config
* horizontal gallery changes to the next slide when user scrolls up or down

### PR DESCRIPTION
**Pull request by harm-less**
Fixes #161.

The direction for HammerJS panning is limited to only horizontal or vertical depending on your preference both for the gallery and the thumbs.

I also changed the `CONTRIBUTION.MD` file as the `prepare-build` task was called `init-build` as far as I could see.

### CODE REVIEW

**Comment by MurhafSousli** [comment]
@harm-less Thanks for the PR, I will review it asap

**Comment by MurhafSousli** [comment]
@harm-less This is great, I have been looking for this fix for while!

**Comment by harm-less** [comment]
Glad you like it mate!
When do you think you'll issue a new release?

**Comment by MurhafSousli** [comment]
@harm-less Try `v4.0.0-beta.0`

**Comment by harm-less** [comment]
It works as expected 😄 
Thanks for the effort of making that beta

**Pull request merged**
