### PR TITLE
Add support for Vimeo videos

### PR DESCRIPTION
**Pull request by ChrisMBarr**
Now videos from Vimeo.com can be added to a gallery just like YouTube by simply provide the video ID from the URL.  For example this video: https://vimeo.com/124139626 is embedded like so:
```ts
{
  type: 'vimeo',
  autoplay: false,
  src: '124139626'
} as VimeoItemData,
```

Here's a screen recording of that Vimeo video working on the demo page.

vimeo-demo

Searching through old issues, this addresses additional concerns already addressed by #22, and might possibly address #539

The only thing not covered by this PR is updating [all the wiki pages that mention youtube](https://github.com/search?q=repo%3AMurhafSousli%2Fngx-gallery+youtube&type=wikis) to also have mentions and code examples of Vimeo as well.

### CODE REVIEW

**Comment by ChrisMBarr** [comment]
I have resolved the merge issues since the v11 update, and I've tested this, and it's still working just fine.

Some logic around fetching a Vimeo thumbnail got a lot simpler than before, I opened an issue over there and it was resolved. For reference: https://github.com/ThatGuySam/vumbnail/issues/42

**Comment by ChrisMBarr** [comment]
This PR has been sitting here for over a year now. I have just resolved the merge conflict regarding the new control-flow syntax.

**Comment by MurhafSousli** [comment]
Hi @ChrisMBarr  I am sorry - I think the last time I looked into this it had conflicts. Could you rebase the PR? it would be better to squash your commits into one.

**Comment by ChrisMBarr** [comment]
Can you just do a squash merge? I am able to do this on projects that I own 
image

**Pull request merged**
