### PR TITLE
Removed HttpClientModule dependency from the GalleryModule

### LINKED ISSUE #277: Interceptor not called in lazy-loading module with imported GalleryModule
#### What is the current behavior?
When I importing the GalleryModule in lazy-loading module my interceptor stops working in this module. I suppose that happens because I use the HttpClientModule in AppModule and in GalleryModule also used HttpClientModule. But I should import HttpClientModule only once, see [docs](https://angular.io/guide/http#setup-installing-the-module)

What can I do to resolve this problem?

#### Which versions are you using for the following packages?

Angular: 7.0.0
Angular CDK: 7.1.0
Angular CLI: 7.0.2
Typescript: 3.1.1
Gallery: 4.0.2-beta.0

### PR DESCRIPTION
**Pull request by harm-less**
Fixes #277 

There's a whole threat about this issue in one of the Angular issues and I agree with this person commenting on the previous message: [https://github.com/angular/angular/issues/20575](https://github.com/angular/angular/issues/20575#issuecomment-526221149)

This PR would fix all of the problems all the people from #277 (and myself) are having, so I hope you agree with this solution. The only big downside is that this change is no longer backwards compatible. So it might mean a major release, but I leave that up to you as I think a lot of people already import the HttpClientModule anyway.

### CODE REVIEW

**Comment by MurhafSousli** [comment]
How about removing the whole feature `mode=determinate`?

**Comment by harm-less** [comment]
I'm not quite sure, I don't know why it's bugged but it does sound a like a nice feature visually.
I'd say, if you can fix the `determinate` issue go for it, otherwise remove the feature.

**Comment by MurhafSousli** [comment]
@harm-less I have re-written a new carousel plugin from scratch but I couldn't get the time to finalize it.

That's why I don't want to invest more time in this one. but since it is still useful for many. I am looking for maintainers.

**Comment by harm-less** [comment]
Sounds cool! 😄 
Why a new one though?

I'm not looking to actively maintain a repo at the moment. If I were you I'd merge your latest PR and remove the HttpClientModule for the Core module. Ignore this PR then as it's no longer required. That should cover some of anguish from a few people and shouldn't cost you any time.

For backwards compatibility reasons you might want to keep the `loadingMode` input as deprecated (not functional I guess) and release a minor release.

**Comment by harm-less** [comment]
Hey mate,
Do you think you'll be able to merge both open PR's somewhere this month?

**Comment by elvirdolic** [comment]
@MurhafSousli it's impossible to use the lib in lazy loaded module when a second HttpClientModule is imported all http intercedptors are ignroed. Please check!!

**Pull request closed without merging**
