### PR TITLE
Add click handler to gallery component

### PR DESCRIPTION
**Pull request by AIOrc**
Added click handler to component chain `gallery` `>` `gallery-core` `>` `gallery-slider` to allow for interactions.
E.g.: Open lightbox on gallery item click.

### CODE REVIEW

**Comment by AIOrc** [comment]
@MurhafSousli - Hope I'm not overstepping!

**Comment by MurhafSousli** [comment]
Hi @AIOrc, no not at all.
The user may have an iframe slide or his own slide component that might have buttons, Would not this cause conflict if the slide has buttons and gallery emits its container click events at the same time?

**Comment by MurhafSousli** [comment]
The `itemClick` event is added in the upcoming update (version 3), but you will not need to use the itemClick event for your use case because gallerize directive also got updated, so the usage will become like:

```html
<gallery gallerize></gallery>
```

then any item click will open the gallery in lightbox.

Thanks for your PR, but I have to close it since we have a major update, the click event will be implemented in every gallery item's template.

**Comment by AIOrc** [comment]
@MurhafSousli - sounds brilliant! I was not aware of the new major version, sorry about that!
I can't wait for it then :)
Thanks for taking the time to explain.

**Comment by MurhafSousli** [comment]
@AIOrc it is on, check https://murhafsousli.github.io/ngx-gallery/#/gallerize

**Pull request closed without merging**
